/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-10-06 06:46:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;
import portfolio.datadto;
import java.util.List;
import portfolio.datadto;
import java.util.List;

public final class config_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/./footer2.jsp", Long.valueOf(1696550010144L));
    _jspx_dependants.put("/./main2.jsp", Long.valueOf(1696573397461L));
    _jspx_dependants.put("/./top2.jsp", Long.valueOf(1696574644031L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("portfolio.datadto");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Date today = new Date();
	DateFormat df = new SimpleDateFormat("yyyMMddhms");
	String dates = df.format(today);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/page_default.css?v=");
      out.print(dates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/admin_css.css?v=");
      out.print(dates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\">\r\n");
      out.write("<title>관리자 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav>\r\n");
      out.write('\r');
      out.write('\n');

	String username = (String) session.getAttribute("username");
	String name = (String) session.getAttribute("name");

      out.write("\r\n");
      out.write("<div class=\"menusize\">\r\n");
      out.write("    <ul id=\"menus\">\r\n");
      out.write("        <li class=\"topmenu1\">ADMINISTRATOR</li>\r\n");
      out.write("        <li class=\"topmenu2\">환경설정</li>\r\n");
      out.write("        <li class=\"topmenu2\">회원관리</li>\r\n");
      out.write("        <li class=\"topmenu2\">공지사항 관리</li>\r\n");
      out.write("        <li class=\"topmenu2\">1:1 문의사항</li>\r\n");
      out.write("        <li class=\"topmenu2\">예약현황</li>\r\n");
      out.write("        <li class=\"topmenu2\">권리자현황</li>\r\n");
      out.write("        ");
 if (username != null && !username.isEmpty()) { 
      out.write("\r\n");
      out.write("            <li class=\"topmenu3\">");
      out.print( name );
      out.write("님 환영합니다  <a href=\"/logout.do\">[로그아웃]</a></li>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <li class=\"topmenu3\"><a href=\"./index.jsp\">[로그인]</a></li>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("<div class=\"menuline\"></div>");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<main class=\"page_main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<datadto> admins = (List<datadto>)request.getAttribute("admins");
	int totalAdmins = (Integer)request.getAttribute("totalAdmins");
	int limit = 10;
	int totalPages = (int) Math.ceil((double) totalAdmins / limit); // 전체 페이지 수
	String pageStr = request.getParameter("page");
	int currentPage = (pageStr != null) ? Integer.parseInt(pageStr) : 1; // 현재 페이지 번호
	
	if(currentPage < 1) currentPage = 1; // 현재 페이지 번호가 1보다 작으면 1로 설정
	if(currentPage > totalPages) currentPage = totalPages; // 현재 페이지 번호가 전체 페이지 수보다 크면 전체 페이지 수로 설정

      out.write("\r\n");
      out.write("<section class=\"page_section\">\r\n");
      out.write("<form id=\"frm\" name=\"frm\" method=\"post\" onsubmit=\"return member_search();\">    \r\n");
      out.write("<div class=\"listbody\">\r\n");
      out.write(" <div class=\"adlisttitle\">관리자 현황</div>\r\n");
      out.write(" <div class=\"procho\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li class=\"prochoL procfont\">소속</li>\r\n");
      out.write("        <li class=\"prochoL\">\r\n");
      out.write("            <select class=\"adlistcsel1\" id=\"affiliationSelect\">\r\n");
      out.write("                <option value=\"\">전체</option>\r\n");
      out.write("                <option value=\"본사\">본사</option>\r\n");
      out.write("                <option value=\"경기도\">경기도</option>\r\n");
      out.write("                <option value=\"인천\">인천</option>\r\n");
      out.write("                <option value=\"대전\">대전</option>\r\n");
      out.write("                <option value=\"세종\">세종</option>\r\n");
      out.write("                <option value=\"광주\">광주</option>\r\n");
      out.write("                <option value=\"대구\">대구</option>\r\n");
      out.write("                <option value=\"울산\">울산</option>\r\n");
      out.write("                <option value=\"전라남도\">전라남도</option>\r\n");
      out.write("                <option value=\"전라북도\">전라북도</option>\r\n");
      out.write("                <option value=\"충청남도\">충청남도</option>\r\n");
      out.write("                <option value=\"충청북도\">충청북도</option>\r\n");
      out.write("                <option value=\"경상남도\">경상남도</option>\r\n");
      out.write("                <option value=\"경상북도\">경상북도</option>\r\n");
      out.write("                <option value=\"제주도\">제주도</option>  \r\n");
      out.write("            </select>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"procho\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li class=\"prochoL procfont\">검색형식</li>\r\n");
      out.write("        <li class=\"prochoL\">\r\n");
      out.write("            <select class=\"adlistcsel1\" name=\"search_part\">\r\n");
      out.write("                <option>이름</option>\r\n");
      out.write("                <option>아이디</option>\r\n");
      out.write("                <option>연락처</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"prochoL\"><input type=\"text\" class=\"adlistcsel1\" name=\"search\"></li>\r\n");
      out.write("        <li class=\"prochoL\"><input type=\"submit\" id=\"searchBtn\" class=\"proclick\" value=\"검색\"></li>\r\n");
      out.write("        <li class=\"prochoL\"><button type=\"button\" class=\"proclick\">전체</button></li>\r\n");
      out.write("    </ul>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"protaball\">\r\n");
      out.write("    <table width=\"1100\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr style=\"color: white; background-color: rgb(67, 66, 66);\">\r\n");
      out.write("                <td class=\"listcenter\" width=50>NO</td>\r\n");
      out.write("                <td class=\"listcenter\" width=150>구분</td>\r\n");
      out.write("                <td class=\"listcenter\" width=150>아이디</td>\r\n");
      out.write("                <td class=\"listcenter\" width=120>이름</td>\r\n");
      out.write("                <td class=\"listcenter\" width=80>직책</td>\r\n");
      out.write("                <td class=\"listcenter\" width=200>이메일</td>\r\n");
      out.write("                <td class=\"listcenter\" width=120>연락처</td>\r\n");
      out.write("                <td class=\"listcenter\" width=120>현황</td>\r\n");
      out.write("                <td class=\"listcenter\" width=110>적용</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            ");
 
            if (admins == null || admins.size() == 0) {
            
      out.write("\r\n");
      out.write("                <tr height=\"30\"><td class=\"listcenter\" colspan=\"9\">등록된 관리자가 없습니다.</td></tr>\r\n");
      out.write("            ");
 
            } else {
                for (datadto admin : admins) {
            
      out.write("\r\n");
      out.write("                    <tr class=\"master_list\">\r\n");
      out.write("                        <td class=\"listcenter\">");
      out.print(admin.getId());
      out.write("</td>\r\n");
      out.write("                        <td class=\"listcenter\">");
      out.print(admin.getAffiliation());
      out.write("</td>\r\n");
      out.write("                        <td class=\"listcenter\">");
      out.print(admin.getUsername());
      out.write("</td>\r\n");
      out.write("                        <td class=\"listcenter\">");
      out.print(admin.getName());
      out.write("</td>\r\n");
      out.write("                        <td class=\"listcenter\">");
      out.print(admin.getPosition());
      out.write("</td>\r\n");
      out.write("                        <td class=\"listcenter\">");
      out.print(admin.getEmail());
      out.write("</td>\r\n");
      out.write("                        <td class=\"listcenter\">");
      out.print(admin.getPhone_prefix() + admin.getPhone_number());
      out.write("</td>\r\n");
      out.write("                        <td class=\"listcenter\">\r\n");
      out.write("						    <select class=\"adlistsel3\" id=\"status-");
      out.print( admin.getId() );
      out.write("\">\r\n");
      out.write("						        <option ");
      out.print( admin.getStatus().equals("근무중") ? "selected" : "" );
      out.write(">근무중</option>\r\n");
      out.write("						        <option ");
      out.print( admin.getStatus().equals("퇴직중") ? "selected" : "" );
      out.write(">퇴직중</option>\r\n");
      out.write("						    </select>\r\n");
      out.write("						</td>\r\n");
      out.write("                        <td class=\"listcenter\"><button type=\"button\" class=\"listclick\" onclick=\"updateStatus(");
      out.print( admin.getId() );
      out.write(")\">적용</button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("            ");

                }
            }
            
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write(" </div>\r\n");
      out.write("<div class=\"propagebt\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"");
      out.print("/config_main.do?page=" + (currentPage > 1 ? currentPage - 1 : 1) );
      out.write('"');
      out.write(' ');
      out.print( currentPage == 1 ? "style='color: #ccc;'" : "" );
      out.write(" > < </a></li>\r\n");
      out.write("		");
 for(int i = 1; i <= totalPages; i++) { 
      out.write("\r\n");
      out.write("		<li><a href=\"/config_main.do?page=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a></li>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		<li><a href=\"");
      out.print("/config_main.do?page=" + (currentPage < totalPages ? currentPage + 1 : totalPages) );
      out.write('"');
      out.write(' ');
      out.print( currentPage == totalPages ? "style='color: #ccc;'" : "" );
      out.write(" > > </a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("<div class=\"menusize\">Copyright ⓒ 2023 Raemian 분양안내 관리 시스템 All rights reserved</div>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"./js/adm_option.js?v=");
      out.print(dates);
      out.write("\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
